- hosts: "localhost"
  vars_files:
          - vars.yml
  tasks:
          - name: "LoadBalancer"
            ec2:
                    key_name: "Nitya"
                    instance_type: "t2.micro"
                    image: "ami-0a9d27a9f4f5c0efc"
                    wait: yes
                    count: 1
                    instance_tags:
                            Name: LB
                    vpc_subnet_id: "subnet-d13438b9"
                    assign_public_ip: yes
                    region: "ap-south-1"
                    group_id: "sg-0eddb601a985d4da0"
                    aws_access_key: "{{ access_Key }}"
                    aws_secret_key: "{{ secret_Key }}"
          - name: "WebServer"
            ec2:
                    key_name: "Nitya"
                    instance_type: "t2.micro"
                    image: "ami-0a9d27a9f4f5c0efc"
                    wait: yes
                    count: 2
                    instance_tags:
                            Name: WS
                    vpc_subnet_id: "subnet-d13438b9"
                    assign_public_ip: yes
                    region: "ap-south-1"
                    group_id: "sg-0eddb601a985d4da0"
                    aws_access_key: "{{ access_Key }}"
                    aws_secret_key: "{{ secret_Key }}"
