- name: install httpd
  package:
          name: "httpd"
          state: present
- name: copy content
  copy:
          content: "This is {{ ansible_hostname }}"
          dest: /var/www/html/index.html
- name: service start
  service:
          name: "httpd"
          state: started
